import Breadcrumbs from "@/components/breadcrumbs"

import type { Metadata } from 'next'
 
export const metadata: Metadata = {
  title: 'Bizim haqqımızda',
  description: '...',
  image: './about.jpg'
}

export default function About() {
    return (
        <>
            <Breadcrumbs title={metadata.title} image={metadata.image} />

            <div className="container my-10">
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Hic officiis voluptatum eius rerum voluptatibus? Ipsum, ea, ad itaque vero officiis dignissimos autem error deleniti mollitia excepturi, unde nam voluptatum ex pariatur quia architecto placeat? Sequi similique perferendis accusamus laboriosam quis harum molestias! Impedit cupiditate, maiores aliquam nobis nam tempora incidunt nostrum dignissimos. Deleniti itaque quo maiores ullam, eaque officia corporis neque delectus consequuntur dolores magni beatae veritatis dignissimos natus vero atque repudiandae consectetur exercitationem nemo dicta ducimus eius quos totam quia. Ratione debitis sunt repudiandae, dolores ab inventore provident nemo error non? Molestiae facere cupiditate nisi amet, officiis possimus. Nam.
                <br /><br />
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique molestiae nostrum non ducimus sit alias beatae error, aspernatur, asperiores, quo ab aut! Esse porro at fuga quibusdam perspiciatis veniam commodi ullam, voluptates hic rem quis dicta, labore provident dolor dolore sint nobis obcaecati sit voluptate unde expedita vero exercitationem! Quas temporibus vitae esse facilis delectus odio dolorem minima eaque perspiciatis culpa, voluptatibus nemo. Suscipit excepturi ipsa quis consectetur laudantium error, illo dolorum harum alias quas itaque, facere adipisci, totam architecto doloribus officiis tenetur quasi qui tempora! Excepturi culpa eveniet omnis necessitatibus ullam est ab fugit, ipsa accusamus corrupti mollitia distinctio odio asperiores placeat, adipisci consequuntur! Tenetur, veritatis id quo ullam deserunt neque delectus minus quae accusamus quis perferendis fugit dignissimos nulla, tempora doloremque autem architecto voluptatum odio ad repellendus? Rem sit aliquam, magnam vitae, atque officia nulla iste placeat eaque consequatur reiciendis incidunt perferendis mollitia rerum veritatis odio laboriosam magni sunt exercitationem facilis temporibus? Distinctio architecto odit reiciendis quo nesciunt, nulla unde dicta dolorem quod dolorum, excepturi necessitatibus nemo expedita nam cumque quaerat quos nihil? Illo reiciendis consectetur, eius mollitia laborum nisi animi unde ipsum ex itaque molestiae perferendis libero. Eligendi impedit quia beatae dolorem molestias incidunt laborum dolores nulla!
                <br /><br /><br />
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Placeat quia laudantium, fugiat non unde esse voluptatum nostrum dolore rerum voluptatibus incidunt dolorem natus, nihil vel, saepe illum reprehenderit facilis eveniet laboriosam odio? At quaerat neque esse repellendus consectetur adipisci harum vel, molestias natus deleniti voluptas placeat accusantium necessitatibus aliquam temporibus ut incidunt. Praesentium est exercitationem, aspernatur harum facere eligendi deleniti, eum earum, iste culpa tempora! Ea iusto rem dolores ducimus. Natus, accusamus amet fuga optio nemo deleniti facilis. Ea, asperiores autem nam deleniti veniam ex ipsam. Esse dicta error commodi eum voluptatem. Cupiditate explicabo doloribus debitis, voluptatum quis suscipit dolorem modi quo soluta voluptate architecto eligendi reiciendis tempora consequuntur, doloremque illum? Nisi animi error fuga nesciunt ipsam aliquid obcaecati, molestiae cupiditate. Officia cupiditate exercitationem porro corporis eos magnam eveniet vero, alias, sequi quam ea ducimus molestias quae quibusdam? Ducimus porro optio id officia similique suscipit voluptas provident qui veniam earum quam nam repudiandae adipisci quidem, unde aliquid dolorem dolores excepturi magnam rem voluptatibus ad! Modi quibusdam est dignissimos odit commodi nihil harum excepturi laboriosam amet eos quis autem exercitationem velit incidunt, aspernatur rerum non, aperiam praesentium beatae cumque blanditiis cupiditate. Possimus eligendi dolore suscipit vel ad ex sit iste consequatur! Nulla quia ducimus illo quae iste blanditiis voluptates corporis, exercitationem incidunt quis deleniti sequi modi natus suscipit veritatis eaque voluptatibus libero ea possimus ullam quam, recusandae rerum in. Cupiditate saepe nostrum suscipit quaerat dolores tempore culpa architecto laudantium veritatis illo ea doloremque nam, repudiandae facilis nesciunt porro deleniti pariatur eum libero beatae inventore officiis maiores? At nobis modi facilis beatae assumenda. In iste nobis, vitae libero earum saepe voluptate sint veniam ipsam facere explicabo voluptates molestiae, excepturi sequi atque, magnam obcaecati reprehenderit optio necessitatibus autem laborum impedit aliquam. Temporibus, ipsam repudiandae. Laudantium nihil asperiores nostrum fuga eaque aliquam accusamus totam.
            </div>
        </>
    )
}