
import type { Metadata } from "next";
import { Lexend } from "next/font/google";
import "./globals.css";
import FooterSite from "@/components/footer";
import NavigationSite from "@/components/navigation";


const lexend = Lexend({ 
    subsets: ['latin'], 
    weight: ['200', '400', '700'], 
    variable: '--font-lexend'
 });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body className={lexend.className}>
          <NavigationSite/>    
          
          {children}

          <FooterSite></FooterSite>
      </body>
    </html>
  );
}
